version: '3.8'

services:
  mongo:
    image: mongo:5
    command: ['--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
    volumes:
      - mongo1:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongo:27017\"}]}).ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
      interval: 10s
      start_period: 30s
      timeout: 5s

  backend:
    build:
      context: .
      target: production
    depends_on:
      - mongo
    env_file:
      - .env

  frontend:
    build:
      context: ./outer-chat.client
      target: production
    depends_on:
      - backend
    env_file:
      - ./outer-chat.client/.env

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  mongo1:
  caddy_data:
  caddy_config:
